version: "2"
run:
  timeout: 5m
  go: "1.25"
  build-tags: []
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: false
  issues-exit-code: 1
  tests: true
output:
  formats: {}
linters:
  enable:
    - goprintffuncname
    - errcheck
    - intrange
    - forbidigo
    - funcorder
    - nilnesserr
    - ireturn
    - nestif
    - testableexamples
    - dupword
    - reassign
    - lll
    - mnd
    - decorder
    - unparam
    - usestdlibvars
    - durationcheck
    - errname
    - testpackage
    - tagliatelle
    - thelper
    - modernize
    - canonicalheader
    - gocritic
    - nolintlint
    - protogetter
    - recvcheck
    - forcetypeassert
    - exptostd
    - whitespace
    - gomoddirectives
    - testifylint
    - depguard
    - revive
    - mirror
    - perfsprint
    - gosec
    - dupl
    - spancheck
    - inamedparam
    - staticcheck
    - gochecknoinits
    - prealloc
    - nilnil
    - maintidx
    - unconvert
    - exhaustruct
    - containedctx
    - wsl_v5
    - tparallel
    - nakedret
    - gosmopolitan
    - noctx
    - fatcontext
    - sqlclosecheck
    - zerologlint
    - unused
    - godox
    - usetesting
    - godot
    - nlreturn
    - noinlineerr
    - importas
    - paralleltest
    - iotamixing
    - nosprintfhostport
    - arangolint
    - dogsled
    - nonamedreturns
    - tagalign
    - rowserrcheck
    - sloglint
    - govet
    - funlen
    - ineffassign
    - goconst
    - iface
    - wrapcheck
    - gocognit
    - asciicheck
    - predeclared
    - contextcheck
    - errorlint
    - gochecksumtype
    - unqueryvet
    - ginkgolinter
    - copyloopvar
    - gocyclo
    - gocheckcompilerdirectives
    - gomodguard
    - bidichk
    - varnamelen
    - godoclint
    - err113
    - goheader
    - cyclop
    - misspell
    - nilerr
    - bodyclose
    - makezero
    - embeddedstructfieldcheck
    - grouper
    - asasalint
    - gochecknoglobals
    - promlinter
    - wastedassign
    - exhaustive
    - loggercheck
    - interfacebloat
formatters:
  enable:
    - golines
issues: {}
