version: "2"
run:
    timeout: 5m
    go: "1.25"
    build-tags: []
    modules-download-mode: readonly
    allow-parallel-runners: true
    allow-serial-runners: false
    issues-exit-code: 1
    tests: true
output:
    formats: {}
linters:
    enable:
        - makezero
        - errcheck
        - bidichk
        - nonamedreturns
        - funlen
        - nakedret
        - gochecknoglobals
        - mnd
        - modernize
        - unqueryvet
        - testableexamples
        - goconst
        - revive
        - decorder
        - embeddedstructfieldcheck
        - godot
        - zerologlint
        - dupl
        - tparallel
        - unconvert
        - testifylint
        - nolintlint
        - lll
        - containedctx
        - copyloopvar
        - gosec
        - unused
        - godox
        - spancheck
        - importas
        - nosprintfhostport
        - godoclint
        - gochecksumtype
        - gocyclo
        - unparam
        - maintidx
        - prealloc
        - rowserrcheck
        - noctx
        - sloglint
        - dupword
        - grouper
        - gocritic
        - contextcheck
        - cyclop
        - gomoddirectives
        - usestdlibvars
        - nilerr
        - bodyclose
        - iface
        - gochecknoinits
        - fatcontext
        - durationcheck
        - interfacebloat
        - loggercheck
        - mirror
        - protogetter
        - whitespace
        - nilnesserr
        - nestif
        - varnamelen
        - govet
        - usetesting
        - gocognit
        - intrange
        - misspell
        - wrapcheck
        - forbidigo
        - tagliatelle
        - funcorder
        - recvcheck
        - ginkgolinter
        - perfsprint
        - inamedparam
        - tagalign
        - goprintffuncname
        - errorlint
        - canonicalheader
        - promlinter
        - testpackage
        - wastedassign
        - ireturn
        - gomodguard
        - asasalint
        - exhaustive
        - staticcheck
        - sqlclosecheck
        - ineffassign
        - thelper
issues: {}
