version: "2"
run:
  timeout: 5m
  go: "1.25"
  build-tags: []
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: false
  issues-exit-code: 1
  tests: true
output:
  formats: {}
linters:
  enable:
    - wsl_v5
    - tparallel
    - godot
    - exhaustive
    - errchkjson
    - goprintffuncname
    - gomoddirectives
    - depguard
    - nilnil
    - godox
    - nosprintfhostport
    - sloglint
    - gochecksumtype
    - intrange
    - durationcheck
    - gocritic
    - recvcheck
    - inamedparam
    - staticcheck
    - noinlineerr
    - unqueryvet
    - protogetter
    - mirror
    - spancheck
    - dogsled
    - gocheckcompilerdirectives
    - varnamelen
    - embeddedstructfieldcheck
    - canonicalheader
    - exptostd
    - revive
    - dupl
    - zerologlint
    - wrapcheck
    - grouper
    - asasalint
    - funcorder
    - forcetypeassert
    - unconvert
    - importas
    - bidichk
    - nilerr
    - promlinter
    - wastedassign
    - tagliatelle
    - modernize
    - maintidx
    - reassign
    - decorder
    - perfsprint
    - nakedret
    - gosmopolitan
    - govet
    - goconst
    - cyclop
    - errcheck
    - unparam
    - thelper
    - gosec
    - fatcontext
    - usetesting
    - paralleltest
    - arangolint
    - nilnesserr
    - testifylint
    - exhaustruct
    - tagalign
    - iface
    - goheader
    - makezero
    - gochecknoglobals
    - noctx
    - gocognit
    - misspell
    - musttag
    - forbidigo
    - bodyclose
    - sqlclosecheck
    - iotamixing
    - rowserrcheck
    - asciicheck
    - errorlint
    - gocyclo
    - gomodguard
    - loggercheck
    - ireturn
    - nestif
    - prealloc
    - nlreturn
    - copyloopvar
    - godoclint
    - err113
    - interfacebloat
    - dupword
    - testpackage
    - gochecknoinits
    - unused
    - funlen
    - contextcheck
    - testableexamples
    - mnd
    - usestdlibvars
    - errname
    - nonamedreturns
    - ineffassign
    - predeclared
    - ginkgolinter
    - nolintlint
    - whitespace
    - containedctx
formatters:
  enable:
    - golines
issues: {}
