// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package hobby

import (
	"database/sql"
)

type User struct {
	ID        string        `json:"id"`
	Email     string        `json:"email"`
	FullName  string        `json:"full_name"`
	CreatedAt sql.NullInt64 `json:"created_at"`
	UpdatedAt sql.NullInt64 `json:"updated_at"`
}
