name: issue-template
description: Report a bug or request a feature
title: "[BUG] " or "[FEATURE] "
labels: [bug, enhancement]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!

- type: input
  id: sqlc-wizard-version
  attributes:
    label: SQLC-Wizard Version
    description: What version of SQLC-Wizard are you using?
    placeholder: e.g., v1.0.0, dev, git commit hash
  validations:
    required: true

- type: input
  id: go-version
  attributes:
    label: Go Version
    description: What version of Go are you using?
    placeholder: e.g., 1.25.4
  validations:
    required: true

- type: input
  id: os-platform
  attributes:
    label: Operating System & Architecture
    description: What OS and architecture are you using?
    placeholder: e.g., macOS M1, Ubuntu 22.04, Windows 11
  validations:
    required: true

- type: dropdown
  id: issue-type
  attributes:
    label: Issue Type
    description: What type of issue are you reporting?
    options:
      - Bug Report
      - Feature Request
      - Documentation Issue
      - Performance Issue
      - Security Issue
    default: 0
  validations:
    required: true

- type: textarea
  id: description
  attributes:
    label: Description
    description: A clear and concise description of what the issue is.
    placeholder: Describe the issue or feature request
  validations:
    required: true

- type: textarea
  id: reproduction-steps
  attributes:
    label: Reproduction Steps
    description: Steps to reproduce the issue.
    placeholder: |
      1. Run 'sqlc-wizard init'
      2. Select 'microservice' project type
      3. Choose 'postgresql' database
      4. See error
  validations:
    required: false

- type: textarea
  id: expected-behavior
  attributes:
    label: Expected Behavior
    description: What you expected to happen.
    placeholder: Describe what should have happened
  validations:
    required: false

- type: textarea
  id: actual-behavior
  attributes:
    label: Actual Behavior
    description: What actually happened.
    placeholder: Describe what actually happened
  validations:
    required: false

- type: textarea
  id: error-log
  attributes:
    label: Error Log
    description: Paste the full error log if available.
    render: text
  validations:
    required: false

- type: textarea
  id: additional-context
  attributes:
    label: Additional Context
    description: Any other context about the problem.
    render: markdown
  validations:
    required: false

- type: textarea
  id: sqlc-config
  attributes:
    label: SQLC Configuration (if applicable)
    description: Paste your sqlc.yaml file if the issue is configuration-related.
    render: yaml
    placeholder: |
      version: "2"
      sql:
        - engine: postgresql
          # ... rest of config
  validations:
    required: false

- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our Code of Conduct
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true